### ISSUE TITLE
Chrome Web Store labeling as Unsafe

### ISSUE THREAD

**Issue by elmorekevin** [mattiabasone/CanopyGUIEnhancer#16]
Here's what the error is:
![image](https://user-images.githubusercontent.com/31101710/176935397-a2c3686d-21d1-4155-99bb-46671d72f083.png)

**Comment by mattiabasone** [comment]
I've already submitted a new version with updated policies, I'm waiting for approval.

**Comment by mattiabasone** [comment]
@elmorekevin do you still have this issue?
Chrome web store support told me some days ago that should be ok now.

![image](https://user-images.githubusercontent.com/3951536/178741201-042fadc7-0be1-43cd-a180-217df8ccfa95.png)

**Comment by elmorekevin** [comment]
Just tested it, all seems good! Thanks!
