### ISSUE TITLE
AP Evalatuation > Registered color code

### ISSUE THREAD

**Issue by fwall222** [mattiabasone/CanopyGUIEnhancer#2]
Under Tools>AP Evaluation it's missing 
"Current entry index: 0 Session Status: REGISTERED (via Primary Color Code {{ number }});"

I have to disable the extension in chromium in order to see which color code it's currently registered to.

**Extension version:** Version 1.8.10
**Chromium version:** Version 62.0.3202.89
**OS:** Linux version 4.4.0-64-generic (Linux Mint)
**Radio version:** 5.4/5.7GHz MIMO OFDM - Subscriber Module

**Comment by mattiabasone** [comment]
The color code is missing, but you can click on the anchor "Current entry index: <link to number>" to view more detail about the access point

**Comment by mattiabasone** [comment]
Added in version 1.9.0
