### ISSUE TITLE
13.4.1 PMP100 Data VC page rendering

### ISSUE THREAD

**Issue by elmorekevin** [mattiabasone/CanopyGUIEnhancer#3]
I see that not all features will work with older versions, just checking if this is one of them. Great and amazing tool, I hope Cambium has thanked you profusely!

The page seems to be missing three columns, but I'm not sure which ones. Here's the Console output from Google Chrome:
![image](https://user-images.githubusercontent.com/31101710/34838150-0eb6f13e-f6cb-11e7-8b59-237d4b162b88.png)

**Comment by mattiabasone** [comment]
> I hope Cambium has thanked you profusely!

Ehm...Nope.

I'll take a look at the PMP100 Data VC page

**Comment by elmorekevin** [comment]
Thanks! Working great!
