### ISSUE TITLE
No MAC lookup

### ISSUE THREAD

**Issue by masterskier** [mattiabasone/CanopyGUIEnhancer#5]
MAC lookup was working last week but this week the mouse-over bubble does not appear.
Chrome Version 63.0.3239.132
Thank you

**Comment by mattiabasone** [comment]
There is a problem with the MAC Address lookup API service, I've already reported the problem.

Thanks!

**Comment by masterskier** [comment]
Thanks for your reply.
(The GUI enhancer is great.)
Don
