### ISSUE TITLE
add pps count to the ethernet statistics?

### ISSUE THREAD

**Issue by cchance27** [mattiabasone/CanopyGUIEnhancer#6]
Any chance you could add a Packets Per second (pps) reading to the ethernet page, along with the mbps? Since the datas available?

**Comment by mattiabasone** [comment]
Added in version 1.8.13

**Comment by 903BB** [comment]
Hello , I have added version 1.8.13 but I am having same issue as OP

**Comment by trosiere** [comment]
Yes i am having issues with live usage now that this has been updated.  Cannot see live usage on ethernet tab using graph

**Comment by mattiabasone** [comment]
Can you check the browser console (Ctrl+Shift+i) for errors?

**Comment by 903BB** [comment]
![image](https://user-images.githubusercontent.com/38108799/38382402-77869e62-38cf-11e8-93e5-cf34546baaef.png)

**Comment by mattiabasone** [comment]
Can you take a screenshot of "Console" and "Network" tab of the developer tools? (window on the right) thanks

**Comment by 903BB** [comment]
![image](https://user-images.githubusercontent.com/38108799/38385225-f231ba8c-38d6-11e8-973d-f13f85323d1e.png)

**Comment by 903BB** [comment]
![image](https://user-images.githubusercontent.com/38108799/38385289-197c9030-38d7-11e8-83a7-f838bedd744c.png)

**Comment by mattiabasone** [comment]
Thank you, I've just uploaded a new version (1.8.14) and it will be out soon. Please, tell me if you still have this issue.

**Comment by 903BB** [comment]
Working like a charm now, thank you greatly!!!
