### ISSUE TITLE
Graphing of data and (0 pps) has stopped working

### ISSUE THREAD

**Issue by WirelessNetMan** [mattiabasone/CanopyGUIEnhancer#7]
Just updated to the latest version and looked at the (pages Statistics → Ethernet; Statistics → Radio) graphing of data and (0 pps) has stopped working.

**Comment by mattiabasone** [comment]
Can you check the browser console (Ctrl+Shift+i) for errors?

**Comment by WirelessNetMan** [comment]
It seems to be an issue in Chrome browser and not in Firefox 59.0.2 (64-bit)
Sorry I only check Chrome.

Also: I do not see any errors.

**Comment by drdrewdown** [comment]
Agreed, this has broken the usage meter in string or graph (Chrome)

**Comment by elmorekevin** [comment]
Same here, but sometimes it works, sometimes it doesn't. It maybe seems to work at first, but switching to another page and then back to the tab with the graph causes it to break.

**Comment by mattiabasone** [comment]
Can you provide me more information?
- Cambium device type and model
- Do you have data update issue on other pages (like AP Data VC or Throughput)?
- Screenshot of your settings
- Your Developer tools -> Network -> XHR looks like this https://i.imgur.com/Wm8x5eT.png?

Thank you!

**Comment by drdrewdown** [comment]
1) Cambium AP PMP450i (also PMP450 SM)
2) Blue data rate blocks appears when loading Data VC or Throughput pages, but within a second or two disappear

3)Settings everything is checked but console debug
4) https://imgur.com/a/f4Qp7 (initiator is refresh.js)

**Comment by Bukimari** [comment]
> It seems to be an issue in Chrome browser and not in Firefox 59.0.2 (64-bit)

Oddly enough, I can't get it to display anything for the Throughput on this same version of Firefox. Chrome has the same issue as mentioned in the comment above.

**Comment by elmorekevin** [comment]
Mine seems to get one CanopyEnhancer at the beginning, then goes to Refresh.js
![image](https://user-images.githubusercontent.com/31101710/38384512-5d3a845c-38dd-11e8-8b71-731ca4b1c65d.png)

**Comment by WirelessNetMan** [comment]
I checked and the Firefox version that is working Version 1.8.4.  The
Chrome browser is Version 1.8.13 of CanopyGUIEnhancer

**Comment by drdrewdown** [comment]
Thank you! it appears to be working after latest update to 1.8.14

**Comment by WirelessNetMan** [comment]
Yes,  Thank you for your quick work.! It's working for me after latest
update to 1.8.14
